kind: ReplicationController
apiVersion: v1
metadata:
  name: redis-slave
  labels:
    name: redis-slave
spec:
  replicas: 2
  selector:
    name: redis-slave
  template:
    metadata:
      labels:
        name: redis-slave
    spec:
      containers:
      - name: slave
        image: staubth/redis-slave:v1
        ports:
        - containerPort: 6379
          protocol: TCP

