FROM redis:alpine3.16
MAINTAINER Johannes M. Scheuermann <johannes.scheuermann@inovex.de>

COPY start-redis-master.sh /start-redis-master.sh
RUN chmod +x /start-redis-master.sh
CMD /start-redis-master.sh
